### ISSUE TITLE
Use JavaPoet

### ISSUE THREAD

**Issue by fbiville** [softwarevidal/jax-rs-linker#23]
http://corner.squareup.com/2015/01/javapoet.html is released!

**Comment by malk** [comment]
Codign Java with Strings ?

**Comment by fbiville** [comment]
The main idea is getting the generator closer to the generated code. 
JavaWriter code was totally different from what it's supposed to generate.
JavaPoet gets closer to the symmetry you'd get with a template.

**Comment by malk** [comment]
Yup I get that, I just do not get the real Value ver using a Template. (Is not like it is giving you some type checking). Whyt not just use mustache at that point?

**Comment by fbiville** [comment]
Well, you've got some checks performed for you with JavaPoet versus none for templates.
Plus some integration with [Filer](http://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/Filer.html) API etc etc

**Comment by malk** [comment]
:+1:
