### ISSUE TITLE
Resolve query parameters

### ISSUE THREAD

**Issue by fbiville** [softwarevidal/jax-rs-linker#24]
Very similar to path parameters.
The only difference is there isn't gonna be any validation (we cannot tell what is mandatory from what is not).
Nice to have: pre-populate (maybe in a different multimap) default values (`@DefaultValue`) so users will still get them by default in the resulting URI.

**Comment by fbiville** [comment]
Contrary path parameters, users should be allowed to pass arbitrary (i.e. undeclared with `@QueryParam`) query parameters. Therefore, there should be a second method which accepts `String name, String value` as arguments.

**Comment by fbiville** [comment]
Or maybe leave the user with a compiler option, e.g. `strictQueryParams=true` (only declared `@QueryParam` can be substituted) vs  `strictQueryParams=false` (any query parameter can be appended).

**Comment by jcgay** [comment]
Closed by 137324b.
