### ISSUE TITLE
Guava 18.0 required

### ISSUE THREAD

**Issue by fbiville** [softwarevidal/jax-rs-linker#8]
A priori, deux solutions : 

  1. inliner la dép
  2. s'en débarrasser
  3. ne rien faire

Inconvénient de 1 : Guava est pas exactement un petit JAR et le déploiement devient un peu plus compliqué.
Inconvénient de 2 : on est actuellement fortement couplé à Guava donc faut réécrire plein de trucs (surtout qu'on est en JDK 7)
Inconvénient de 3 : tout projet client avec un Guava < 18 va planter, donc faut le documenter clairement

**Comment by jcgay** [comment]
Que nettoyer son API comme le fait Guava c'est bien mais que ça fout toujours la merde dans la gestion des dépendances :)

On peut essayer de relocaliser Guava et de supprimer les classes non utilisées ([minimizeJar](http://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#minimizeJar)).
Mais si ça ne fonctionne pas je suis pour faire sauter la dépendance à Guava.

**Comment by fbiville** [comment]
Résolu par f6e4c035fe256a9623990e5e2c694caf24d3ba9d.
